<?php

declare(strict_types=1);

namespace Nip\Database\Connections;

use Nip\Database\Query\AbstractQuery;
use Nip\Database\Query\Delete as DeleteQuery;
use Nip\Database\Query\Insert as InsertQuery;
use Nip\Database\Query\Select as SelectQuery;
use Nip\Database\Query\Update as UpdateQuery;
use Nip\Database\Result;

/**
 * Contract for a database connection.
 *
 * Inspired by Symfony DBAL's Connection concept, this interface provides
 * a framework-agnostic contract for interacting with a database.
 *
 * @package Nip\Database\Connections
 */
interface ConnectionInterface
{
    /**
     * Connect to the database server.
     */
    public function connect(string $host, string $user, string $password, string $database, bool $newLink = false): static;

    /**
     * Disconnect from the database server.
     */
    public function disconnect(): void;

    /**
     * Execute a raw SQL string or a query object and return a Result.
     *
     * @param AbstractQuery|string $query
     */
    public function execute(AbstractQuery|string $query): Result;

    /**
     * Return a new SELECT query builder bound to this connection.
     */
    public function newSelect(): SelectQuery;

    /**
     * Return a new INSERT query builder bound to this connection.
     */
    public function newInsert(): InsertQuery;

    /**
     * Return a new UPDATE query builder bound to this connection.
     */
    public function newUpdate(): UpdateQuery;

    /**
     * Return a new DELETE query builder bound to this connection.
     */
    public function newDelete(): DeleteQuery;

    /**
     * Return a new query builder of the given type bound to this connection.
     *
     * @param string $type  select|insert|update|delete|replace|truncate
     */
    public function newQuery(string $type = 'select'): AbstractQuery;

    /**
     * Return the ID generated by the last INSERT statement.
     */
    public function lastInsertID(): int|string;

    /**
     * Return the number of rows affected by the last DML statement.
     */
    public function affectedRows(): int;

    /**
     * Return the name of the currently selected database.
     */
    public function getDatabase(): string;

    /**
     * Escape and quote a table/column identifier using back-ticks.
     */
    public function protect(string $input): string;

    // -------------------------------------------------------------------------
    // Symfony DBAL-style parameterised execution
    // -------------------------------------------------------------------------

    /**
     * Execute a parameterised SELECT (or any query that returns rows).
     *
     * When the underlying adapter implements
     * {@see \Nip\Database\Adapters\PreparedStatementAdapterInterface} (e.g.
     * the PDO adapter) the values are passed as bound parameters; otherwise
     * the call falls back to a plain `execute($sql)` so the MySQLi adapter
     * continues to work unchanged.
     *
     * ```php
     * // Raw SQL
     * $result = $conn->executeQuery('SELECT * FROM users WHERE id = ?', [42]);
     *
     * // Query builder
     * [$sql, $params] = $conn->newSelect()->from('users')->where('id = ?', 42)->toSql();
     * $result = $conn->executeQuery($sql, $params);
     * ```
     *
     * @param  array<int|string, mixed> $params  Positional (`?`) binding values.
     */
    public function executeQuery(string $sql, array $params = []): Result;

    /**
     * Execute a parameterised INSERT / UPDATE / DELETE and return the affected-row count.
     *
     * ```php
     * $affected = $conn->executeStatement(
     *     'UPDATE users SET active = ? WHERE id = ?',
     *     [1, 42]
     * );
     * ```
     *
     * @param  array<int|string, mixed> $params  Positional (`?`) binding values.
     */
    public function executeStatement(string $sql, array $params = []): int;
}
