<?php

declare(strict_types=1);

namespace Nip\Database\Connections;

use Nip\Database\Query\AbstractQuery;
use Nip\Database\Query\Delete as DeleteQuery;
use Nip\Database\Query\Insert as InsertQuery;
use Nip\Database\Query\Select as SelectQuery;
use Nip\Database\Query\Update as UpdateQuery;
use Nip\Database\Result;

/**
 * Contract for a database connection.
 *
 * Inspired by Symfony DBAL's Connection concept, this interface provides
 * a framework-agnostic contract for interacting with a database.
 *
 * @package Nip\Database\Connections
 */
interface ConnectionInterface
{
    /**
     * Connect to the database server.
     */
    public function connect(string $host, string $user, string $password, string $database, bool $newLink = false): static;

    /**
     * Disconnect from the database server.
     */
    public function disconnect(): void;

    /**
     * Execute a raw SQL string or a query object and return a Result.
     *
     * @param AbstractQuery|string $query
     */
    public function execute(AbstractQuery|string $query): Result;

    /**
     * Return a new SELECT query builder bound to this connection.
     */
    public function newSelect(): SelectQuery;

    /**
     * Return a new INSERT query builder bound to this connection.
     */
    public function newInsert(): InsertQuery;

    /**
     * Return a new UPDATE query builder bound to this connection.
     */
    public function newUpdate(): UpdateQuery;

    /**
     * Return a new DELETE query builder bound to this connection.
     */
    public function newDelete(): DeleteQuery;

    /**
     * Return a new query builder of the given type bound to this connection.
     *
     * @param string $type  select|insert|update|delete|replace|truncate
     */
    public function newQuery(string $type = 'select'): AbstractQuery;

    /**
     * Return the ID generated by the last INSERT statement.
     */
    public function lastInsertID(): int|string;

    /**
     * Return the number of rows affected by the last DML statement.
     */
    public function affectedRows(): int;

    /**
     * Return the name of the currently selected database.
     */
    public function getDatabase(): string;

    /**
     * Escape and quote a table/column identifier using back-ticks.
     */
    public function protect(string $input): string;
}
